name: dev

on:
  push:
    branches:
      - dev

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: run tests
        run: mvn -B install --file pom.xml